"use client";import{useEffect,useState}from"react";import{useParams,useRouter}from"next/navigation";import{supabase}from"@/lib/supabase";
export default function EditCourse(){const{ id }=useParams<{id:string}>();const router=useRouter();const[course,setCourse]=useState<any>(null),[chapters,setChapters]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function load(){const{data:c,error:ce}=await supabase.from("courses").select("*").eq("id",id).single();if(ce){setError(ce.message);setLoading(false);return}const{data:ch,error:che}=await supabase.from("chapters").select("*,lessons(*)").eq("course_id",id).order("position");if(che)setError(che.message);setCourse(c);setChapters((ch||[]).map(x=>({...x,lessons:(x.lessons||[]).sort((a:any,b:any)=>a.position-b.position)})));setLoading(false)}
useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user){router.push("/login");return}const{data:p}=await supabase.from("profiles").select("role").eq("id",u.user.id).single();if(p?.role!=="admin"){router.push("/");return}load()})()},[id,router]);
async function saveCourse(e:any){e.preventDefault();setBusy(true);const{error}=await supabase.from("courses").update({title:course.title,slug:course.slug,description:course.description,difficulty:course.difficulty,status:course.status}).eq("id",id);if(error)setError(error.message);else await load();setBusy(false)}
async function addChapter(){const title=prompt("Chapter / Unit title");if(!title)return;const position=chapters.length;const{error}=await supabase.from("chapters").insert({course_id:id,title,position});if(error)setError(error.message);else load()}
async function addLesson(ch:any){const title=prompt("Lesson title");if(!title)return;const position=(ch.lessons||[]).length;const{error}=await supabase.from("lessons").insert({chapter_id:ch.id,title,position,xp_reward:10,estimated_minutes:10});if(error)setError(error.message);else load()}
async function togglePublish(){const next=course.status==="published"?"draft":"published";const{error}=await supabase.from("courses").update({status:next}).eq("id",id);if(error)setError(error.message);else load()}
if(loading)return <div className="screen-center"><div className="spinner"/></div>;if(!course)return <main className="main"><div className="error">{error||"Course not found"}</div></main>;
return <main className="main"><button className="back-link" onClick={()=>router.push("/admin")}>← Admin</button><div className="page-head"><p className="eyebrow">COURSE BUILDER</p><h1>{course.title}</h1><p className="muted">Build the learning path, then publish it when ready.</p></div>{error&&<div className="error">{error}</div>}<form className="auth-card" onSubmit={saveCourse}><label>Title<input value={course.title} onChange={e=>setCourse({...course,title:e.target.value})}/></label><label>Slug<input value={course.slug} onChange={e=>setCourse({...course,slug:e.target.value})}/></label><label>Description<input value={course.description||""} onChange={e=>setCourse({...course,description:e.target.value})}/></label><label>Difficulty<select value={course.difficulty||"Beginner"} onChange={e=>setCourse({...course,difficulty:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><div style={{display:"flex",gap:10}}><button className="primary-btn" disabled={busy}>{busy?"Saving…":"Save Course"}</button><button type="button" className="secondary-btn" style={{margin:0}} onClick={togglePublish}>{course.status==="published"?"Unpublish":"Publish"}</button></div></form><div className="section"><div className="section-head"><h2>Units & Lessons</h2><button className="primary-btn" style={{padding:"8px 12px"}} onClick={addChapter}>+ Unit</button></div>{chapters.map((ch,i)=><div className="chapter" key={ch.id}><div className="chapter-title"><span>{String(i+1).padStart(2,"0")}</span><div><h3>{ch.title}</h3><p>{ch.description||"Learning unit"}</p></div></div>{ch.lessons.map((l:any)=><button className="lesson-row" key={l.id} onClick={()=>router.push("/admin/lessons/"+l.id)}><span>○</span><span><strong>{l.title}</strong><small>{l.estimated_minutes||10} min · +{l.xp_reward||10} XP</small></span><span>EDIT →</span></button>)}<button className="secondary-btn" style={{margin:"14px 0 0",width:"100%"}} onClick={()=>addLesson(ch)}>+ Add Lesson</button></div>)}{!chapters.length&&<div className="empty-card"><span>🧱</span><h3>Start the path</h3><p>Add the first unit, then add lessons inside it.</p></div>}</div></main>}